### ISSUE TITLE
Adapter Modules

### ISSUE THREAD

**Issue by Epi-NMT** [NLP2CT/Meta-Curriculum#3]
I am trying to find the code of the adapter modules that Meta-NMT added to the model.
They don't mention the details in the paper and the code is hard to understand.
Since Meta-Curriculum uses most of their code, so I hope this question can be answered here.

Thank you!

**Comment by Ririkoo** [comment]
Hi keyu07,

Our Meta-Curriculum did not use the adapter module. If you want to use the adapter module that Meta-NMT used, I would suggest you refer to this file: fairseq/models/transformer.py. They implemented the adapter architecture in this file. 
Hope it would be helpful.

**Comment by Epi-NMT** [comment]
Thank you for your reply, that is very helpful.
One more quick question:
So if I am not mistaken, your base model was the vanilla model trained on WMT14 and without any modifications on the model, right?

**Comment by Ririkoo** [comment]
Yes. We used the vanilla Transformer model.
