### ISSUE TITLE
Datasets are different

### ISSUE THREAD

**Issue by Epi-NMT** [NLP2CT/Meta-Curriculum#4]
I am testing a vanilla T5-small model recently but get very low Bleus on almost every domain data. 
I found that we have different amounts of sentences for each domain.
I guess you have filtered the data so I wonder if you can share me your datasets.

**Comment by Ririkoo** [comment]
Yes, we filtered the data according to the sentence length as we mentioned in the original paper. 
But there are still some problems with the OPUS corpus in terms of data quality, which we have not found before. 
Therefore, to make a fair comparison, I would like to suggest taking the results reported in a subsequent work (Table 2) as the reference: https://arxiv.org/pdf/2112.08288.pdf. They reproduced the experiments on a cleaner benchmark and further improved the performance. 

I also recommend conducting the adaptation experiments on another benchmark:  https://arxiv.org/abs/2004.02105. They improved the quality of the OPUS corpus with the help of data selection. I also used this benchmark in my recent research work.

**Comment by Ririkoo** [comment]
Hi  @keyu07,

I tested vanilla T5-small model on domain-specific translation tasks. The zero-shot setting of T5-small underperforms the vanilla Transformer model. If you want to achieve higher BLEU scores, you may try:

1. Pre-train T5 model on WMT19 data then fine-tune it on domain-specific data.
2. Switch to a larger model like T5-base/large.

**Comment by Epi-NMT** [comment]
> 
Thanks for your reply and the information.

I figured out why I keep getting low bleu scores, just because of some default settings of huggingface.
I have better bleu scores on covid, bible and books, where they are 32, 19 and 15 respectively. 
Lower bleu on ECB, which is 27, and other domains are still running right now.

**Comment by Ririkoo** [comment]
Glad to see that! 

Please note that pre-training T5 on WMT19 data will largely improve the performance. For example, vanilla T5-large achieve 15.4 BLEU on my Bible test split, and it will increase to 33 BLEU score after pre-training & fine-tuning.
